version: '3.7'

services:
  database:
    image: mysql:5.7
    restart: always
    networks:
      - docker_network
    environment:
      MYSQL_DATABASE: testlink_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: testlink
      MYSQL_PASSWORD: testlink
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  testlink:
    image: bitnami/testlink
    container_name: testlink
    restart: always
    ports:
      - ${PORT_HTTP:-80}:80
    networks:
      - testlink-network
    volumes:
      - testlink_data:/bitnami
    depends_on:
      - mariadb
    environment:
      - TESTLINK_DATABASE_NAME=${DATABASE_NAME}
      - TESTLINK_DATABASE_USER=${DATABASE_USER}
      - TESTLINK_DATABASE_PASSWORD=${DATABASE_PASS}
      - TESTLINK_USERNAME=${TESTLINK_USERNAME}
      - TESTLINK_PASSWORD=${TESTLINK_PASSWORD}
      - TESTLINK_EMAIL=${TESTLINK_EMAIL}
      - TESTLINK_LANGUAGE=pt_BR
      - SMTP_ENABLE=${SMTP_ENABLE:-false}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_CONNECTION_MODE=${SMTP_CONNECTION_MODE}

volumes:
  mariadb_testlink_data:
    name: mariadb_testlink_data
  testlink_data:
    name: testlink_data

networks:
  testlink-network:
    name: testlink-network
    driver: bridge
